
import { Language } from './types';

export const TRANSLATIONS = {
  en: {
    app_name: 'BookLend',
    dashboard: 'Dashboard',
    catalog: 'Catalog',
    my_loans: 'My Loans',
    admin_panel: 'Admin Panel',
    requests: 'Loan Management',
    manage_books: 'Manage Books',
    activity_logs: 'Activity Logs',
    switch_role: 'Switch Role',
    notifications: 'Notifications',
    no_notifications: 'No new notifications',
    search_placeholder: 'Search for books, authors...',
    filter_genre: 'Filter by Genre',
    all_genres: 'All Genres',
    available: 'Available',
    out_of_stock: 'Out of Stock',
    rent_now: 'Rent Now',
    daily_rate: 'Daily Rate',
    rent_days: 'Rental Days',
    total_cost: 'Total Cost',
    confirm_rent: 'Confirm Rental',
    cancel: 'Cancel',
    status: 'Status',
    due_date: 'Due Date',
    penalty: 'Penalty',
    return_book: 'Return Book',
    approve: 'Approve',
    reject: 'Reject',
    add_book: 'Add New Book',
    edit_book: 'Edit Book',
    title: 'Title',
    author: 'Author',
    copies: 'Total Copies',
    image_url: 'Image URL',
    save: 'Save Changes',
    create: 'Create Book',
    login_as: 'Logged in as',
    welcome: 'Welcome back',
    days: 'days',
    currency: 'IQD ',
    active_loans: 'Active Loans',
    overdue: 'Overdue',
    pending: 'Pending Approval',
    success_rent: 'Rental request submitted!',
    success_return: 'Book returned successfully!',
    success_update: 'Book updated successfully!',
    success_create: 'Book created successfully!',
    fee_breakdown: 'Fee Breakdown',
    base_fee: 'Base Fee',
    late_fee: 'Late Fee',
    book_details: 'Book Details',
    description: 'Description',
    view_details: 'View Details',
    close: 'Close',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    full_name: 'Full Name',
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    logout: 'Logout',
    login_success: 'Logged in successfully',
    signup_success: 'Account created successfully',
    invalid_credentials: 'Invalid email or password',
    demo_admin: 'Demo Admin',
    demo_member: 'Demo Member',
    dashboard_overview: 'Dashboard Overview',
    total_revenue: 'Total Revenue',
    monthly_revenue: 'Monthly Revenue',
    total_books: 'Total Books',
    low_stock: 'Low Stock Alert',
    quick_stats: 'Quick Stats',
    revenue_chart: 'Revenue & Activity',
    attention_needed: 'Attention Needed',
    no_pending_requests: 'No pending requests',
    view_all: 'View All',
    actions: 'Actions',
    stock: 'Stock',
    recent_activity: 'Recent Activity',
    filter_status: 'Filter Status',
    all_loans: 'All Loans',
    returned: 'Returned',
    no_logs: 'No activity logs found.',
    log_rent_request: 'Loan Requested',
    log_loan_approved: 'Loan Approved',
    log_loan_rejected: 'Loan Rejected',
    log_book_returned: 'Book Returned',
    log_book_added: 'Book Added',
    log_book_updated: 'Book Updated',
    profile: 'Profile',
    edit_profile: 'Edit Profile',
    member_since: 'Member Since',
    total_loans: 'Total Loans',
    loan_history: 'Loan History',
    avatar_url: 'Avatar URL',
    returned_loans: 'Returned Loans',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    leave_blank: 'Leave blank to keep current password',
    passwords_mismatch: 'Passwords do not match',
    profile_updated: 'Profile updated successfully',
    forgot_password: 'Forgot Password?',
    reset_password: 'Reset Password',
    send_reset_link: 'Send Reset Link',
    back_to_login: 'Back to Login',
    reset_email_sent: 'Password reset link sent to your email.',
    enter_email_reset: 'Enter your email to receive reset instructions.',
    new_label: 'New',
    growth_label: 'growth',
    role_admin: 'Admin',
    role_member: 'Member',
    promote_admin: 'Promote to Admin',
    demote_member: 'Demote to Member',
    genre_fiction: 'Fiction',
    genre_science: 'Science',
    genre_history: 'History',
    genre_technology: 'Technology',
    genre_philosophy: 'Philosophy',
    genre_art: 'Art',
  },
  ar: {
    app_name: 'إعارة كتب',
    dashboard: 'لوحة التحكم',
    catalog: 'المكتبة',
    my_loans: 'إعاراتي',
    admin_panel: 'لوحة الإدارة',
    requests: 'إدارة الإعارات',
    manage_books: 'إدارة الكتب',
    activity_logs: 'سجل النشاطات',
    switch_role: 'تغيير الدور',
    notifications: 'إشعارات',
    no_notifications: 'لا توجد إشعارات جديدة',
    search_placeholder: 'ابحث عن كتب، مؤلفين...',
    filter_genre: 'تصفية حسب النوع',
    all_genres: 'كل الأنواع',
    available: 'متاح',
    out_of_stock: 'غير متوفر',
    rent_now: 'استأجر الآن',
    daily_rate: 'السعر اليومي',
    rent_days: 'مدة الإعارة',
    total_cost: 'التكلفة الإجمالية',
    confirm_rent: 'تأكيد الإعارة',
    cancel: 'إلغاء',
    status: 'الحالة',
    due_date: 'تاريخ الاستحقاق',
    penalty: 'غرامة',
    return_book: 'إرجاع الكتاب',
    approve: 'قبول',
    reject: 'رفض',
    add_book: 'إضافة كتاب جديد',
    edit_book: 'تعديل الكتاب',
    title: 'العنوان',
    author: 'المؤلف',
    copies: 'عدد النسخ',
    image_url: 'رابط الصورة',
    save: 'حفظ التغييرات',
    create: 'إنشاء كتاب',
    login_as: 'تم تسجيل الدخول بصفة',
    welcome: 'أهلاً بك',
    days: 'أيام',
    currency: 'د.ع ',
    active_loans: 'إعارات نشطة',
    overdue: 'متأخر',
    pending: 'قيد الانتظار',
    success_rent: 'تم إرسال طلب الإعارة!',
    success_return: 'تم إرجاع الكتاب بنجاح!',
    success_update: 'تم تحديث الكتاب بنجاح!',
    success_create: 'تم إنشاء الكتاب بنجاح!',
    fee_breakdown: 'تفاصيل الرسوم',
    base_fee: 'الرسوم الأساسية',
    late_fee: 'رسوم التأخير',
    book_details: 'تفاصيل الكتاب',
    description: 'الوصف',
    view_details: 'عرض التفاصيل',
    close: 'إغلاق',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    full_name: 'الاسم الكامل',
    dont_have_account: "ليس لديك حساب؟",
    already_have_account: "لديك حساب بالفعل؟",
    logout: 'تسجيل الخروج',
    login_success: 'تم تسجيل الدخول بنجاح',
    signup_success: 'تم إنشاء الحساب بنجاح',
    invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    demo_admin: 'تجربة كمسؤول',
    demo_member: 'تجربة كعضو',
    dashboard_overview: 'نظرة عامة',
    total_revenue: 'إجمالي الإيرادات',
    monthly_revenue: 'إيرادات الشهر',
    total_books: 'إجمالي الكتب',
    low_stock: 'تنبيه المخزون المنخفض',
    quick_stats: 'إحصائيات سريعة',
    revenue_chart: 'الإيرادات والنشاط',
    attention_needed: 'يتطلب اهتمام',
    no_pending_requests: 'لا توجد طلبات معلقة',
    view_all: 'عرض الكل',
    actions: 'إجراءات',
    stock: 'المخزون',
    recent_activity: 'النشاط الأخير',
    filter_status: 'تصفية الحالة',
    all_loans: 'كل الإعارات',
    returned: 'مرجعة',
    no_logs: 'لا توجد سجلات نشاط.',
    log_rent_request: 'طلب إعارة',
    log_loan_approved: 'تمت الموافقة',
    log_loan_rejected: 'تم الرفض',
    log_book_returned: 'تم الإرجاع',
    log_book_added: 'تم إضافة كتاب',
    log_book_updated: 'تم تحديث كتاب',
    profile: 'الملف الشخصي',
    edit_profile: 'تعديل الملف الشخصي',
    member_since: 'عضو منذ',
    total_loans: 'إجمالي الإعارات',
    loan_history: 'سجل الإعارات',
    avatar_url: 'رابط الصورة الرمزية',
    returned_loans: 'الإعارات المرجعة',
    new_password: 'كلمة المرور الجديدة',
    confirm_password: 'تأكيد كلمة المرور',
    leave_blank: 'اترك الحقل فارغاً للاحتفاظ بكلمة المرور الحالية',
    passwords_mismatch: 'كلمتا المرور غير متطابقتين',
    profile_updated: 'تم تحديث الملف الشخصي بنجاح',
    forgot_password: 'نسيت كلمة المرور؟',
    reset_password: 'إعادة تعيين كلمة المرور',
    send_reset_link: 'إرسال رابط إعادة التعيين',
    back_to_login: 'العودة لتسجيل الدخول',
    reset_email_sent: 'تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني.',
    enter_email_reset: 'أدخل بريدك الإلكتروني لاستلام تعليمات إعادة التعيين.',
    new_label: 'جديد',
    growth_label: 'نمو',
    role_admin: 'مدير',
    role_member: 'عضو',
    promote_admin: 'ترقية لمدير',
    demote_member: 'تنزيل لعضو',
    genre_fiction: 'خيال',
    genre_science: 'علوم',
    genre_history: 'تاريخ',
    genre_technology: 'تكنولوجيا',
    genre_philosophy: 'فلسفة',
    genre_art: 'فن',
  },
  ku: {
    app_name: 'BookLend',
    dashboard: 'داشبۆرد',
    catalog: 'کتێبخانە',
    my_loans: 'قەرزەکانم',
    admin_panel: 'پەنێڵی بەڕێوەبەر',
    requests: 'بەڕێوەبردنی قەرزەکان',
    manage_books: 'بەڕێوەبردنی کتێبەکان',
    activity_logs: 'تۆماری چالاکییەکان',
    switch_role: 'گۆڕینی ڕۆڵ',
    notifications: 'ئاگانامەکان',
    no_notifications: 'هیچ ئاگانامەیەکی نوێ نییە',
    search_placeholder: 'گەڕان بۆ کتێب، نووسەر...',
    filter_genre: 'فلتەرکردن بەپێی چەشن',
    all_genres: 'هەموو چەشنەکان',
    available: 'بەردەستە',
    out_of_stock: 'لە کۆگا نەماوە',
    rent_now: 'ئێستا بەکرێ بگرە',
    daily_rate: 'نرخی ڕۆژانە',
    rent_days: 'ڕۆژانی بەکرێگرتن',
    total_cost: 'کۆی تێچوو',
    confirm_rent: 'تأکیدکردنەوەی بەکرێگرتن',
    cancel: 'هەڵوەشاندنەوە',
    status: 'دۆخ',
    due_date: 'بەرواری گەڕاندنەوە',
    penalty: 'غەرامە',
    return_book: 'گەڕاندنەوەی کتێب',
    approve: 'پەسەندکردن',
    reject: 'ڕەتکردنەوە',
    add_book: 'زیادکردنی کتێبی نوێ',
    edit_book: 'دەستکاریکردنی کتێب',
    title: 'ناونیشان',
    author: 'نووسەر',
    copies: 'کۆی کۆپییەکان',
    image_url: 'بەستەری وێنە',
    save: 'خەزنکردنی گۆڕانکارییەکان',
    create: 'دروستکردنی کتێب',
    login_as: 'چوونەژوورەوە وەک',
    welcome: 'بەخێربێیتەوە',
    days: 'ڕۆژ',
    currency: 'د.ع ',
    active_loans: 'قەرزە چالاکەکان',
    overdue: 'دواکەوتوو',
    pending: 'چاوەڕوانکردن',
    success_rent: 'داواکاری بەکرێگرتن نێردرا!',
    success_return: 'کتێبەکە بە سەرکەوتوویی گەڕێندرایەوە!',
    success_update: 'کتێبەکە نوێکرایەوە!',
    success_create: 'کتێبەکە دروستکرا!',
    fee_breakdown: 'وردەکاری تێچوو',
    base_fee: 'تێچووی بنەڕەتی',
    late_fee: 'تێچووی دواکەوتن',
    book_details: 'وردەکاری کتێب',
    description: 'وەسف',
    view_details: 'بینینی وردەکارییەکان',
    close: 'داخستن',
    login: 'چوونەژوورەوە',
    signup: 'تۆمارکردن',
    email: 'ئیمەیڵ',
    password: 'وشەی تێپەڕ',
    full_name: 'ناوی تەواو',
    dont_have_account: "هەژمارت نییە؟",
    already_have_account: "پێشتر هەژمارت هەبووە؟",
    logout: 'چوونەدەرەوە',
    login_success: 'بە سەرکەوتوویی چوویتە ژوورەوە',
    signup_success: 'هەژمار بە سەرکەوتوویی دروستکرا',
    invalid_credentials: 'ئیمەیڵ یان وشەی تێپەڕ هەڵەیە',
    demo_admin: 'دێمۆی بەڕێوەبەر',
    demo_member: 'دێمۆی ئەندام',
    dashboard_overview: 'پوختەی داشبۆرد',
    total_revenue: 'کۆی داهات',
    monthly_revenue: 'داهاتی مانگانە',
    total_books: 'کۆی کتێبەکان',
    low_stock: 'ئاگادارکردنەوەی کەمی کۆگا',
    quick_stats: 'ئاماری خێرا',
    revenue_chart: 'داهات و چالاکی',
    attention_needed: 'پێویستی بە سەرنجە',
    no_pending_requests: 'هیچ داواکارییەک نییە',
    view_all: 'بینینی هەموو',
    actions: 'کردارەکان',
    stock: 'کۆگا',
    recent_activity: 'چالاکی ئەم دواییە',
    filter_status: 'فلتەرکردنی دۆخ',
    all_loans: 'هەموو قەرزەکان',
    returned: 'گەڕێندراوەتەوە',
    no_logs: 'هیچ تۆمارێکی چالاکی نەدۆزرایەوە.',
    log_rent_request: 'داوای قەرزکراو',
    log_loan_approved: 'قەرز پەسەندکرا',
    log_loan_rejected: 'قەرز ڕەتکرایەوە',
    log_book_returned: 'کتێب گەڕێندرایەوە',
    log_book_added: 'کتێب زیادکرا',
    log_book_updated: 'کتێب نوێکرایەوە',
    profile: 'پرۆفایل',
    edit_profile: 'دەستکاریکردنی پرۆفایل',
    member_since: 'ئەندام لە',
    total_loans: 'کۆی قەرزەکان',
    loan_history: 'مێژووی قەرز',
    avatar_url: 'بەستەری وێنە',
    returned_loans: 'قەرزە گەڕێندراوەکان',
    new_password: 'وشەی تێپەڕی نوێ',
    confirm_password: 'تأکیدکردنەوەی وشەی تێپەڕ',
    leave_blank: 'بە بەتاڵی بەجێی بهێڵە بۆ هێشتنەوەی وشەی تێپەڕی ئێستا',
    passwords_mismatch: 'وشەکانی تێپەڕ لێکچوو نین',
    profile_updated: 'پرۆفایل بە سەرکەوتوویی نوێکرایەوە',
    forgot_password: 'وشەی تێپەڕت لەبیرچووە؟',
    reset_password: 'ڕێکخستنەوەی وشەی تێپەڕ',
    send_reset_link: 'ناردنی بەستەری ڕێکخستنەوە',
    back_to_login: 'گەڕانەوە بۆ چوونەژوورەوە',
    reset_email_sent: 'بەستەری ڕێکخستنەوە بۆ ئیمەیڵەکەت نێردرا.',
    enter_email_reset: 'ئیمەیڵەکەت بنووسە بۆ وەرگرتنی ڕێنماییەکانی ڕێکخستنەوە.',
    new_label: 'نوێ',
    growth_label: 'گەشە',
    role_admin: 'بەڕێوەبەر',
    role_member: 'ئەندام',
    promote_admin: 'بەرزکردنەوە بۆ بەڕێوەبەر',
    demote_member: 'داشکاندن بۆ ئەندام',
    genre_fiction: 'خەیاڵی',
    genre_science: 'زانستی',
    genre_history: 'مێژوویی',
    genre_technology: 'تەکنەلۆژیا',
    genre_philosophy: 'فەلسەفە',
    genre_art: 'هونەر',
  }
};

export const CONSTANTS = {
  LATE_PENALTY_FLAT: 5.00,
  LATE_PENALTY_DAILY: 1.00,
  DEFAULT_IMAGES: {
    BOOK: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=300&h=450",
    AVATAR_API: "https://ui-avatars.com/api/?background=10b981&color=fff&bold=true&length=1&name="
  }
};
